Do not create lists if not necessary, use generator expressions
INM-6/python-dicthash pull request #16
Opened 2017-04-13 20:47 UTC by jakobj

This PR removes three occurences where we created lists, while generator expressions are sufficient.

2017-04-14 02:53 UTC, mschmidt87 requested changes
Very elegant. Just one minor request.

2017-04-14 02:53 UTC, mschmidt87 commented on dicthash/dicthash.py
> +    return ''.join(_unpack_value(d[key], prefix + unicode(key)) for key in sorted(whitelist))
It is unrelated to the topic of the PR, but we should still change this:
`prefix` is a keyword argument to `_unpack_value` so we should use it like this. Thus, please insert a `prefix=prefix+...` here.

2017-04-17 13:09 UTC, jakobj commented
thanks for the comment. I've now rebased onto master and addressed the issue you raised.

2017-04-28 07:57 UTC, mschmidt87 reviewed
I can't judge what you changed in the last round, but my complaint remains, see line comment.

2017-04-28 07:57 UTC, mschmidt87 commented on dicthash/dicthash.py
> +    return ''.join(_unpack_value(d[key], prefix + str(key)) for key in sorted(whitelist, key=str))
It is unrelated to the topic of the PR, but we should still change this:
prefix is a keyword argument to _unpack_value so we should use it like this. Thus, please insert a prefix=prefix+... here.

2017-04-28 12:45 UTC, jakobj commented
Haha, apperently nothing. Wait a second...

2017-04-28 12:51 UTC, jakobj commented
I think I now managed to finally include your comment. ;)

2017-04-29 01:12 UTC, mschmidt87 approved these changes

2017-04-29 01:12 UTC, merged