Add setup script and adapt README
INM-6/python-dicthash pull request #17
Opened 2017-04-13 21:07 UTC by jakobj

2017-04-14 04:58 UTC, mschmidt87 requested changes

2017-04-14 04:58 UTC, mschmidt87 commented on README.md
>  ========
Nice work. What about adding a python blob for 2.7 and 3.5 in addition?
You can check the README of the h5py_wrapper for example code. The python 3.5 blob can be linked similarly, like so: https://img.shields.io/badge/python-3.5-blue.svg

2017-04-14 04:58 UTC, mschmidt87 commented on setup.py
> +        'Programming Language :: Python :: 2.7',
To avoid another pull request, can you add 3.5 here and make this PR depend on #13 ?

2017-04-17 13:22 UTC, jakobj commented
Thanks for the comments. I've now added Python2.7/3.5 badges and adapted `setup.py` to also include Python3.5.

2017-04-28 07:59 UTC, mschmidt87 approved these changes

2017-04-28 07:59 UTC, merged