Enh/py37 support
INM-6/python-dicthash pull request #41
Opened 2019-08-24 14:56 UTC by mschmidt87

This PR adds Python 3.7 to the Continuous Integration and documents support for Python 3.7 in the README file.

Relies on #40 .

2019-08-24 17:16 UTC, jakobj commented
thanks, but conda on travis seems to complain that there's no python 3.7 available. that's strange, do you have any idea why this fails? also please resolve the conflicts generated by merging the other PRs

2019-08-25 01:23 UTC, mschmidt87 commented
I think the problem was that our CI was based on miniconda2, which apparently doesn't contain python 3.7. I switched it to miniconda3 and now the CI passes.

2019-08-26 09:19 UTC, jakobj requested changes
just one change, otherwise :+1:

2019-08-26 09:19 UTC, jakobj commented on README.md
> +[![Python3.6](https://img.shields.io/badge/python-3.7-red.svg)](https://www.python.org/)
this should read `Python3.7`

2019-08-27 09:08 UTC, jakobj approved these changes

2019-08-27 09:08 UTC, merged